# Generated by Django 3.2.9 on 2021-11-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college_name',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=65),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=None),
        ),
    ]
