# Generated by Django 3.2.9 on 2021-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211116_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_profile',
            field=models.BooleanField(default=False),
        ),
    ]
