# Generated by Django 3.2.9 on 2021-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_has_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year_of_study',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1),
        ),
    ]
